version: "3.8"
services:
  app:
    build: .
    container_name: doc-retrieval-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
  streamlit:
    build: .
    container_name: doc-retrieval-streamlit
    working_dir: /app
    command: streamlit run app/streamlit_chat.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - app
